export const categoriasWorkingHoliday = [
  { id: 1, name: 'Alemania' },
  { id: 2, name: 'Andorra' },
  { id: 3, name: 'Austria' },
  { id: 4, name: 'Australia' },
  { id: 5, name: 'Canada' },
  { id: 6, name: 'Corea' },
  { id: 7, name: 'Dinamarca' },
  { id: 8, name: 'Eslovaquia' },
  { id: 9, name: 'España' },
  { id: 10, name: 'Francia' },
  { id: 11, name: 'Holanda' },
  { id: 12, name: 'Hungria' },
  { id: 13, name: 'Irlanda' },
  { id: 14, name: 'Luxemburgo' },
  { id: 15, name: 'Japon' },
  { id: 16, name: 'Mexico' },
  { id: 17, name: 'Noruega' },
  { id: 18, name: 'NuevaZelanda' },
  { id: 19, name: 'Polonia' },
  { id: 20, name: 'Portugal' },
  { id: 21, name: 'Republica Checa' },
  { id: 22, name: 'Suecia' },
];
